### ISSUE TITLE
[FEATURE] Use-case-driven "Agent API"

### ISSUE THREAD

**Issue by aggre** [dev-protocol/dev-kit-js#683]
### Detailed description

Implement use-case-driven "Agent APIs" that perform the appropriate APIs for your use case, even if a Provider is connected to an L1/L2 network.

_**Agent APIs are implemented by multiple functions, but this issue aims to add the first one function for starting a new staking position.**_

Therefore, the designs shown below are shared by all functions in the Agent APIs that are expected to be added in the future.

# File structure
- `/lib/`
    - `/agent/` ← NEW!
        - `index.ts`
        - `positionsGet.ts`
        - `positionsCreate.ts`
        - …
    - `/common/`
    - `/ethereum/`
    - `/l2/`
    - `addresses.ts`
    - `index.ts`

# Functions

## positionsCreate
`positionsCreate` function creates a new staking position.

### Typing

```ts
import { Provider } from '@ethersproject/abstract-provider'
import { Signer } from '@ethersproject/abstract-signer'
import { TransactionResponse } from '@ethersproject/abstract-provider'
import { FallbackableOverrides } from '/lib/common/utils/execute'

type Options = {
    provider: Provider | Signer,
    propertyAddress: string,
    amount: string,
    overrides?: FallbackableOverrides
}

type positionsCreate = (options: Options) => Promise<TransactionResponse>`
```

#### Calling

When the passed provider is connected to Ethereum or Ropsten, `positionsCreate` function creates the following low-level contract API and calls `depositToProperty`: /lib/ethereum/lockup

When the passed provider is connected to Arbitrum or Arbitrum Rinkeby, `positionsCreate` function creates the following low-level contract API and calls `depositToProperty`: /lib/l2/lockup

#### Cashing

Discovering the network and creating the contract API each time `positionsCreate` is called wastes computer resources.

`positionsCreate` caches the contract API by WeakMap with Provider as the key.

#### Specification change of existing API

`Lockup.depositToProperty` for L1/L2 internally calls `execute`, but replaces its return value with a true/false.

Since `positionsCreate` should return TransactionResponse, rewrite the return value of `Lockup.depositToProperty` as follows.

```diff
export type CreateDepositToPropertyCaller = (
	contract: ethers.Contract
) => (
	propertyAddress: string,
	amount: string,
	overrides?: FallbackableOverrides
- ) => Promise<boolean>
+ ) => Promise<TransactionResponse>

export const createDepositToPropertyCaller: CreateDepositToPropertyCaller =
	(contract: ethers.Contract) =>
	async (
		propertyAddress: string,
		amount: string,
		overrides?: FallbackableOverrides
	) =>
		execute<MutationOption>({
			contract,
			method: 'depositToProperty',
			mutation: true,
			args: [propertyAddress, amount],
			overrides,
-		}).then(T)
+		})
```

### Context

Dev Kit JS mainly provides low-level APIs, so different APIs are provided for Ethereum and Arbitrum (L2), and Dapps developers need to use different APIs for one use case (e.g. staking).

For Dapps development, Dev Kit requires extra knowledge about the difference between networks. I think it is preferable to have one API providing one implementation for one use case.

### Possible implementation

Agent APIs are newly exported APIs, so we'll need to update the `exports` and `files` in package.json, as well as `rollup.config.js`.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Akira-Taniguchi** [comment]
memo

aggre:The Agent APIs are use-case-driven and provides the same interface for different networks. It means developers don't need to know the difference between L1 and L2 or the contract addresses.
